challenges="/web/challenges"
cp="/web/challengepost"
devise="$HOME/Development/ChallengePost/devise"
home="/web/home"
leeroy="$HOME/Development/ChallengePost/leeroy"
models="/web/models"
sso="$HOME/Development/ChallengePost/sso"
hovercard="$HOME/Development/ChallengePost/hovercard"
